//
// Created by Vlad Boroday on 2023-09-21.
//

#ifndef CHESSGAME_SIMPLEENGINE_UTILITIES_STRING_H_
#define CHESSGAME_SIMPLEENGINE_UTILITIES_STRING_H_

class String
{

};

#endif //CHESSGAME_SIMPLEENGINE_UTILITIES_STRING_H_
